name: QA Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0
          cache: 'npm'

      # 3️⃣ Install Cypress dependencies
      - name: Install Cypress dependencies
        run: npm install
        working-directory: ui/automation

      # 4️⃣ Run
