name: QA Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      # 3️⃣ Install Cypress dependencies
      - name: Install Cypress
        run: |
          npm ci
          npx cypress install
        working-directory: ui/automation

      # 4️⃣ Run Cypress tests
      - name: Run Cypress Tests
        run: npx cypress run --browser electron --record false
        working-directory: ui/automation

      # 5️⃣ Install Newman globally
      - name: Install Newman
        run: npm install -g newman@6.2.1

      # 6️⃣ Run Postman API tests
      - name: Run Postman API Tests
        run: |
          newman run ./api/automation/AutomationExerciseAPITestSuite.postman_collection \
          --environment ./api/automation/AutomationExerciseAPIEnv.postman_environment \
          --reporters cli,junit \
          --reporter-junit-export newman-results.xml
