name: QA Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      # 3️⃣ Cache node_modules for nested folder
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ui/automation/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('ui/automation/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Install dependencies
      - name: Install Cypress dependencies
        run: npm install
        working-directory: ui/automation

      # 5️⃣ Run Cypress Tests using npx
      - name: Run Cypress Tests
        run: npx cypress run --browser electron --record false
        working-directory: ui/automation

      # 6️⃣ Install Newman globally
      - name: Install Newman
        run: npm install -g newman@6.2.1

      # 7️⃣ Run Postman API Tests
      - name: Run Postman API Tests
        run: |
          newman run ./api/automation/AutomationExerciseAPITestSuite.postman_collection \
          --environment ./api/automation/AutomationExerciseAPIEnv.postman_environment \
          --reporters cli,junit \
          --reporter-junit-export newman-results.xml
